"""card_up

Revision ID: 00debcaf7794
Revises: 0e8cfe0eca84
Create Date: 2023-11-22 02:34:51.381948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00debcaf7794'
down_revision = '0e8cfe0eca84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'quantity')
    # ### end Alembic commands ###
