"""card_up

Revision ID: 0e8cfe0eca84
Revises: 6b934e11b111
Create Date: 2023-11-22 02:33:29.863018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8cfe0eca84'
down_revision = '6b934e11b111'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('product_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'product_id')
    # ### end Alembic commands ###
