"""card_up2

Revision ID: 11f2cdde057a
Revises: 00debcaf7794
Create Date: 2023-11-22 03:17:03.078729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f2cdde057a'
down_revision = '00debcaf7794'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'img')
    # ### end Alembic commands ###
