"""card_up2

Revision ID: 1fdf9906c702
Revises: 11f2cdde057a
Create Date: 2023-11-22 03:19:51.094287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdf9906c702'
down_revision = '11f2cdde057a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'img')
    # ### end Alembic commands ###
